Repository Sphinx-Society/kaizen-backend, pull requests merged in 2020-05, with the labels that each got.

#4 SSKB-3 Created Issues templates
  .github/ISSUE_TEMPLATE/kaizen-bug-report---.md
  .github/ISSUE_TEMPLATE/kaizen-feature-request----.md
Labels: documentation

#7 SSKB-4 Added pull request template
  .github/PULL_REQUEST_TEMPLATE/kaizen-pull-request.md
Labels: documentation

#5 SSKB-1 Added eslintrc file and eslint libraries
  .eslintrc
  package.json
  server.js
Labels: feature

#10 SSKB-6 Added missing keyword in pull request template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: bug

#12 SSKB-7 Added eslint plugin
  package.json
Labels: bug

#14 SSBK-5 Added ci.yml file to add continuous integration
  .github/workflow/ci.yml
Labels: feature

#35 SSKB-8 Added MongoDB connection
  .env.example
  .eslintrc
  .gitignore
  __test__/dbManager.js
  __test__/mongo.test.js
  config/index.js
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/dbManager.js.html
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/index.js.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
  package.json
  store/mongo.js
Labels: feature

#51 SSKB-50 Added code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation, feature

#53 SSKB-52 Added Contributing Guideline
  CONTRIBUTING.md
Labels: documentation, enhancement

#55 SSKB-54 Fixed name of PR template
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
Labels: bug, documentation

#70 SSKB-69 Created handle errors middlewares
  .env.example
  .eslintrc
  config/index.js
  lib/logger/index.js
  package.json
  server.js
  utils/middleware/errorHandlers.js
  utils/middleware/notFoundHandler.js
  utils/middleware/validationHandler.js
Labels: bug, feature

#73 SSKB-54 Fixed pull request template
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
Labels: bug, documentation

#72 SSKB-43 Created "Create user" endpoint
  .env.example
  .eslintrc
  __test__/api/users.test.js
  __test__/dbManager.js
  __test__/mongo.test.js
  api/routes.js
  api/services/users/controller.js
  api/services/users/handlers/createCredentialsHandler.js
  api/services/users/handlers/createUserHandler.js
  api/services/users/handlers/sendWelcomeEmailHandler.js
  api/services/users/index.js
  api/services/users/network.js
  api/services/users/schema.js
  config/index.js
  lib/mailing/index.js
  lib/mailing/schema.js
  middleware/errorHandlers.js
  middleware/notFoundHandler.js
  middleware/validationHandler.js
  network/response.js
  package.json
  server.js
  store/mongo.js
  utils/mocks/createUserMock.js
Labels: enhancement, feature

#74 SSKB-44 Added "List users" endpoint
  __test__/api/users.test.js
  api/services/users/controller.js
  api/services/users/handlers/paginationHandler.js
  api/services/users/handlers/queryParamsHandler.js
  api/services/users/network.js
  api/services/users/schema.js
  middleware/errorHandlers.js
  network/response.js
  store/mongo.js
Labels: enhancement, feature

#77 SSKB-71 Added users login endpoint and its tests
  .env.example
  .eslintrc
  __test__/api/users.test.js
  api/services/users/controller.js
  api/services/users/handlers/loginUser.js
  api/services/users/network.js
  config/index.js
  package.json
  store/mongo.js
  utils/mocks/userLoginMock.js
Labels: enhancement, feature

#78 SSKB-46 Created 'Update user' endpoint
  __test__/api/users.test.js
  api/services/users/controller.js
  api/services/users/handlers/createUserHandler.js
  api/services/users/handlers/updateObjectHandler.js
  api/services/users/network.js
  api/services/users/schema.js
  store/mongo.js
  utils/mocks/createUserMock.js
  utils/mocks/updateUserMock.js
Labels: enhancement, feature

#79 SSKB-48 Added 'Get profile' endpoint and its tests
  __test__/api/users.test.js
  api/services/users/controller.js
  api/services/users/handlers/searchQueryHandler.js
  api/services/users/network.js
  store/mongo.js
  utils/mocks/createUserMock.js
Labels: enhancement, feature

#80 SSKB-56 Added 'Update profile' endpoint and its tests
  __test__/api/users.test.js
  api/services/users/controller.js
  api/services/users/handlers/searchQueryHandler.js
  api/services/users/network.js
  api/services/users/schema.js
  utils/mocks/updateUserMock.js
Labels: enhancement, feature

#81 SSKB-36 Added AWS to manage uploads to S3
  .env.example
  api/services/users/controller.js
  api/services/users/network.js
  config/index.js
  lib/AWS/index.js
  middleware/uploader.js
  package.json
Labels: enhancement, feature

#82 SSKB-65 Added 'create medical test' endpoint and its tests
  __test__/api/users.test.js
  api/services/users/controller.js
  api/services/users/handlers/createUserHandler.js
  api/services/users/handlers/createUserTestHandler.js
  api/services/users/network.js
  api/services/users/schema.js
  store/mongo.js
  utils/mocks/updateUserMock.js
Labels: enhancement, feature

#83 SSKB-40 Added jwt validation middleware and its tests
  __test__/middleware/jwtMiddleware.test.js
  api/routes.js
  api/services/users/network.js
  middleware/errorMiddleware.js
  middleware/jwtMiddleware.js
  middleware/notFoundMiddleware.js
  middleware/uploaderMiddleware.js
  middleware/validationMiddleware.js
  package.json
  server.js
  utils/strategies/jwt.js
Labels: enhancement, feature

#85 SSKB 40 Fixed test to avoid crashes with other test
  __test__/middleware/jwtMiddleware.test.js
  utils/mocks/tokenMock.js
Labels: bug

#84 SSKB-67 Added a unique id to medical test when created
  __test__/api/users.test.js
  api/services/users/handlers/createUserTestHandler.js
  api/services/users/schema.js
  package.json
  utils/mocks/updateUserMock.js
Labels: enhancement

#86 SSKB-59 Created "List medical tests" endpoint
  __test__/api/users.test.js
  api/services/users/controller.js
  api/services/users/handlers/projectionHandler.js
  api/services/users/network.js
  store/mongo.js
Labels: enhancement, feature

#87 SSKB-60 Added 'Get medical test' endpoint and its tests
  __test__/api/users.test.js
  api/services/users/handlers/projectionHandler.js
  api/services/users/network.js
  api/services/users/schema.js
Labels: enhancement, feature

#88 SSKB-62 Added 'Delete medical test' endpoint and its tests
  __test__/api/users.test.js
  api/services/users/controller.js
  api/services/users/handlers/objectIdHandler.js
  api/services/users/network.js
  store/mongo.js
Labels: enhancement, feature

#89 SSKB-61 Added update medical test endpoint
  __test__/api/users.test.js
  api/services/users/controller.js
  api/services/users/handlers/prefixHandler.js
  api/services/users/network.js
  lib/logger/index.js
  store/mongo.js
Labels: enhancement, feature

#91 SSKB-90 Fixed 'List medical tests' endpoint, now it retrieves all the elements
  __test__/api/users.test.js
  api/services/users/controller.js
  api/services/users/handlers/projectionHandler.js
  api/services/users/network.js
  store/mongo.js
  utils/helpers/objectEmpty.js
Labels: bug

#92 SSKB-64 Added update tests results for users
  .env.example
  __test__/api/users.test.js
  api/services/users/controller.js
  api/services/users/handlers/projectionHandler.js
  api/services/users/network.js
  utils/helpers/objectHelper.js
Labels: enhancement, feature

#93 SSKB-63 created 'get results' endpoint and its tests
  __test__/api/users.test.js
  api/services/users/controller.js
  api/services/users/handlers/projectionHandler.js
  api/services/users/network.js
Labels: enhancement, feature

#96 SSKB-38 Added PDF genetaror
  __test__/api/users.test.js
  __test__/lib/PDF/generator.test.js
  lib/PDF/generator.js
  lib/PDF/templates/results.html
  package.json
Labels: enhancement, feature

#95 SSKB-68 Validated if results of a test exists before deleting it
  __test__/api/users.test.js
  api/services/users/controller.js
Labels: enhancement

#100 SSKB-99 Fixed PDF generator now verify if file exits
  __test__/lib/PDF/generator.test.js
  lib/PDF/generator.js
  package.json
  server.js
Labels: bug

#103 SSKB-102 Fixed PR Template doesn't be recognized by GitHub
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug, documentation

#106 SSKB-101 Fixed delete user enpoint to remove physically a user
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  __test__/api/users.test.js
  api/services/users/controller.js
  store/mongo.js
Labels: bug, documentation

#104 SSKB-58 Added Endpoint to get a PDF document from result test
  api/services/users/controller.js
  api/services/users/network.js
  lib/PDF/generator.js
  lib/PDF/templates/results.html
  results.pdf
Labels: enhancement, feature

#107 SSKB-57 Created 'Reset password' endpoint and its tests
  __test__/api/users.test.js
  api/services/users/controller.js
  api/services/users/handlers/createCredentialsHandler.js
  api/services/users/handlers/createPasswordHandler.js
  api/services/users/handlers/sendEmailHandler.js
  api/services/users/handlers/sendWelcomeEmailHandler.js
  api/services/users/network.js
  lib/mailing/index.js
Labels: enhancement, feature

#108 SSKB-66 Integration uploader images in register user flow
  api/services/users/controller.js
  api/services/users/network.js
  api/services/users/schema.js
  config/index.js
  lib/AWS/download.png
  lib/AWS/index.js
  lib/PDF/generator.js
  lib/PDF/templates/results.html
  lib/logger/index.js
  lib/mailing/index.js
  lib/mailing/schema.js
Labels: enhancement, feature

#109 SSKB-41 Created 'Update template' endpoint and its tests
  __test__/api/templates.test.js
  api/services/shared/handlers/updateObjectHandler.js
  api/services/templates/controller.js
  api/services/templates/network.js
  api/services/templates/schema.js
  api/services/users/controller.js
  utils/mocks/updateTemplateMock.js
Labels: enhancement, feature

#111 SSKB-42 Created 'Delete template' endpoint and its tests
  __test__/api/templates.test.js
  api/services/templates/controller.js
  api/services/templates/network.js
  api/services/users/controller.js
Labels: enhancement, feature

#113 SSKB-39 Added Get template by id endpoint
  __test__/api/templates.test.js
  api/services/templates/controller.js
  api/services/templates/network.js
Labels: feature

#120 SSKB 112 Created "List Templates" endpoint and its tests
  __test__/api/templates.test.js
  api/services/shared/handlers/paginationHandler.js
  api/services/templates/controller.js
  api/services/templates/network.js
  api/services/templates/schema.js
  api/services/users/controller.js
Labels: enhancement, feature

#122 SSKB-121 Added cors middleware
  package.json
  server.js
Labels: enhancement, feature

#124 SSKB-123 SSKB-123 Removed the "created by" and the "disabled" field in template schema
  api/services/templates/schema.js
Labels: enhancement

#126 SSKB-125 Removed upperCase in create templates endpoint and unit required in template schema
  __test__/api/templates.test.js
  api/services/templates/controller.js
  api/services/templates/schema.js
  utils/mocks/createTemplateMock.js
  utils/mocks/updateTemplateMock.js
Labels: enhancement

#110 SSKB-105 Integrated jwtMiddleware to authorize access
  __test__/api/templates.test.js
  __test__/api/users.test.js
  __test__/lib/PDF/generator.test.js
  api/services/templates/network.js
  api/services/users/handlers/loginUser.js
  api/services/users/network.js
  middleware/jwtMiddleware.js
  middleware/scopeValidationMiddleware.js
  utils/mocks/tokenMock.js
  utils/mocks/userLoginMock.js
  utils/strategies/jwt.js
Labels: enhancement, feature

#127 SSKB-114 Added user that modifies a document in database
  api/services/shared/handlers/updateObjectHandler.js
  api/services/users/controller.js
  api/services/users/handlers/createUserHandler.js
  api/services/users/handlers/createUserTestHandler.js
  api/services/users/network.js
  utils/helpers/updatedByHelper.js
Labels: enhancement

#129 SSKB-128 Added user id to paylod of jwt token
  api/services/users/handlers/loginUser.js
Labels: enhancement, feature

#131 SSKB-130 Added id user in login response
  api/services/users/handlers/loginUser.js
Labels: enhancement

#133 SSKB-132 Restricted the information that a user can see based in their role
  api/services/users/controller.js
  api/services/users/handlers/queryParamsHandler.js
  api/services/users/network.js
  utils/mocks/userLoginMock.js
Labels: enhancement

#135 SSKB-115 Added validation that only accepts active user to login
  api/services/users/handlers/loginUser.js
  api/services/users/network.js
  middleware/scopeValidationMiddleware.js
Labels: enhancement

#134 SSKB 118 Modified generator pdf
  __test__/lib/PDF/generator.test.js
  api/services/users/controller.js
  api/services/users/handlers/projectionHandler.js
  api/services/users/network.js
  api/services/users/schema.js
  lib/PDF/generator.js
  lib/PDF/results.pdf
  lib/PDF/templates/results.hbs
  lib/PDF/templates/results.html
  package.json
  results.pdf
Labels: enhancement

#138 SSKB-137 Removed path to conflict in server prod
  lib/PDF/generator.js
Labels: bug

#139 SSKB-136 Added authentication to template routes
  api/services/templates/controller.js
  api/services/templates/network.js
  package.json
  utils/mocks/userLoginMock.js
Labels: enhancement

#141 SSKB-140 Improved pdf downloads
  lib/PDF/generator.js
Labels: bug

#142 SSKB-140 Fixed opts agrs
  lib/PDF/generator.js
Labels: bug

#144 SSKB-140 Fixed agrs from generator pdf
  lib/PDF/generator.js
Labels: bug

#145 SSKB-140 Modified to trace
  lib/PDF/generator.js
Labels: bug

#146 SSKB-140 Modified generator pdf
  lib/PDF/generator.js
Labels: bug

#147 SSKB-140 Removed console to trace
  lib/PDF/generator.js
Labels: bug

#149 SSKB-148 Added documentId to update user endpoint
  api/services/users/schema.js
Labels: enhancement

#151 SSKB-150 Fixed typo un scope validation
  api/services/users/network.js
Labels: bug

#152 SSKB 117 Created a massive user register endpoint
  api/services/users/controller.js
  api/services/users/network.js
  package.json
  utils/helpers/validationHelper.js
Labels: feature

#153 SSKB-143 Enhanced PDF results, added templateId in tests and deleted doctorId and doctorName in tests
  __test__/api/users.test.js
  __test__/lib/PDF/data/result.pdf
  __test__/lib/PDF/generator.test.js
  api/services/users/handlers/createUserTestHandler.js
  api/services/users/handlers/projectionHandler.js
  api/services/users/network.js
  api/services/users/schema.js
  lib/PDF/data/result.pdf
  lib/PDF/generator.js
  lib/PDF/results.pdf
  lib/PDF/templates/results.hbs
  lib/PDF/templates/results.html
  utils/mocks/updateUserMock.js
Labels: enhancement, feature

#155 SSKB-154 Added logging in Sentry
  .env.example
  config/index.js
  middleware/errorMiddleware.js
  package.json
Labels: enhancement, feature

#157 SSKB-156 Added key to subscribe to login response
  api/services/users/handlers/loginUser.js
  config/index.js
Labels: enhancement

#158 SSKB-119 Added push notifications
  api/services/users/network.js
  lib/Notifications/index.js
  package.json
Labels: enhancement

#160 SSKB-117 Fixed async problem with the error file
  api/services/users/controller.js
Labels: bug

#161 SSKB-116 Modified errors to responses
  __test__/lib/PDF/generator.test.js
  api/services/users/controller.js
  api/services/users/handlers/createUserTestHandler.js
  api/services/users/handlers/loginUser.js
  api/services/users/network.js
  config/messages.js
  lib/AWS/index.js
  lib/logger/index.js
  lib/logger/morgan.js
  middleware/errorMiddleware.js
  middleware/scopeValidationMiddleware.js
  package.json
  server.js
  utils/strategies/jwt.js
Labels: enhancement

#163 SSKB-162 Added mimetype validation in insert users endpoint and fixed messages in users.test
  .env.example
  __test__/api/users.test.js
  __test__/lib/PDF/generator.test.js
  api/services/users/controller.js
  api/services/users/handlers/createUserTestHandler.js
  api/services/users/handlers/loginUser.js
  api/services/users/network.js
  config/messages.js
  lib/AWS/index.js
  utils/helpers/validateMimeTypeHelper.js
  utils/mocks/userLoginMock.js
  utils/strategies/jwt.js
Labels: bug, enhancement

#168 SSKB-164 Added name filter in "list users" endpoint and its tests
  __test__/api/users.test.js
  api/services/users/handlers/queryParamsHandler.js
  api/services/users/schema.js
Labels: enhancement

#167 SSKB-165 Modified error management
  __test__/api/users.test.js
  middleware/errorMiddleware.js
  network/response.js
  utils/mocks/userLoginMock.js
Labels: enhancement

#171 SSKB-170 Updated 'update template' schema
  api/services/templates/schema.js
Labels: bug
