Repository Sphinx-Society/kaizen-backend, pull requests merged in 2020-06, with the labels that each got.

#174 SSKB-172 Added validation to update results
  api/services/users/controller.js
  api/services/users/network.js
  api/services/users/schema.js
  config/messages.js
Labels: enhancement

#176 SSKB-175 Integration tests for update results endpoint
  __test__/api/users.test.js
  api/services/users/schema.js
Labels: enhancement

#173 SSKB-159 Added aws uploader in upload profile
  api/services/users/controller.js
Labels: enhancement

#177 SSKB-169 Added test to upgrade coverage
  __test__/api/templates.test.js
  __test__/api/users.test.js
  lib/mailing/index.js
  utils/mocks/createUserMock.js
Labels: enhancement

#179 SSKB-178 Added subscribe to push notifications
  api/services/users/network.js
  api/services/users/schema.js
  config/messages.js
Labels: enhancement

#180 SSKB-178 Fixed subscribe
  api/services/users/network.js
Labels: feature

#182 SSKB-178 Fixed issues schemas
  api/services/users/network.js
  api/services/users/schema.js
Labels: bug

#183 SSKB-181 fixed bug in login user handler when permissions are empty
  api/services/users/handlers/loginUser.js
Labels: bug

#184 SSKB-178 Fixed issues
  api/services/users/network.js
Labels: bug

#185 SSKB-178 Fixed issues
  api/services/users/network.js
Labels: bug
